#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Aicl.Liebre.WebHost
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class DiagnosticoInfo : ServiceStack.Razor.ViewPage<Aicl.Liebre.Model.DiagnosticoInfoResponse>
{

#line hidden

public override void Execute()
{

#line 2 "DiagnosticoInfo.cshtml"
  
ViewBag.Title="aqui ponemos el titulo";
Layout="Info";


#line default
#line hidden
WriteLiteral("\n\n<div");

WriteLiteral(" style=\"background:grey\"");

WriteLiteral(">\n\t<h1>");


#line 8 "DiagnosticoInfo.cshtml"
Write(Model.Empresa.Nombre);


#line default
#line hidden
WriteLiteral("</h1>\n</div>\n\n");

}
}
}
#pragma warning restore 1591
